-- Các trigger để insert dữ liệu
CREATE OR REPLACE TRIGGER INSERT_VIEW_DANG_KY_HOC_PHAN_CON_MO
INSTEAD OF INSERT ON VIEW_DANG_KY_HOC_PHAN_CON_MO
BEGIN
    INSERT INTO DAPH_DANGKY VALUES (:NEW.MASV, :NEW.MAGV, :NEW.MAHP, :NEW.HK, :NEW.NAM, :NEW.MACT, NULL, NULL, NULL, NULL);
END;
/

CREATE OR REPLACE TRIGGER INSERT_VIEW_PHAN_CONG_HOC_PHAN_DON_VI
INSTEAD OF INSERT ON VIEW_PHAN_CONG_HOC_PHAN_DON_VI
BEGIN
    INSERT INTO DAPH_PHANCONG VALUES (:NEW.MAGV, :NEW.MAHP, :NEW.HK, :NEW.NAM, :NEW.MACT);
END;
/

CREATE OR REPLACE TRIGGER INSERT_VIEW_PHAN_CONG_HOC_PHAN_VAN_PHONG_KHOA
INSTEAD OF INSERT ON VIEW_PHAN_CONG_HOC_PHAN_VAN_PHONG_KHOA
BEGIN  
    INSERT INTO DAPH_PHANCONG VALUES (:NEW.MAGV, :NEW.MAHP, :NEW.HK, :NEW.NAM, :NEW.MACT);
END;
/


-- Các trigger để update dữ liệu
-- VIEW_THONG_TIN_NHAN_VIEN_CO_BAN
CREATE OR REPLACE TRIGGER UPDATE_DT_VIEW_THONG_TIN_NHAN_VIEN_CO_BAN
INSTEAD OF UPDATE ON VIEW_THONG_TIN_NHAN_VIEN_CO_BAN
BEGIN
    UPDATE DAPH_NHANSU SET DT = :NEW.DT WHERE MANV = :OLD.MANV;
END;
/

-- VIEW_DANG_KY_GIANG_VIEN
CREATE OR REPLACE TRIGGER UPDATE_DIEMTH_VIEW_DANG_KY_GIANG_VIEN
INSTEAD OF UPDATE ON VIEW_DANG_KY_GIANG_VIEN
BEGIN 
    UPDATE DAPH_DANGKY SET DIEMTH = :NEW.DIEMTH WHERE MASV = :OLD.MASV AND MAGV = :OLD.MAGV AND MAHP = :OLD.MAHP AND HK = :OLD.HK AND NAM = :OLD.NAM AND MACT = :OLD.MACT;
END;
/

CREATE OR REPLACE TRIGGER UPDATE_DIEMQT_VIEW_DANG_KY_GIANG_VIEN
INSTEAD OF UPDATE ON VIEW_DANG_KY_GIANG_VIEN
BEGIN 
    UPDATE DAPH_DANGKY SET DIEMQT = :NEW.DIEMQT WHERE MASV = :OLD.MASV AND MAGV = :OLD.MAGV AND MAHP = :OLD.MAHP AND HK = :OLD.HK AND NAM = :OLD.NAM AND MACT = :OLD.MACT;
END;
/

CREATE OR REPLACE TRIGGER UPDATE_DIEMCK_VIEW_DANG_KY_GIANG_VIEN
INSTEAD OF UPDATE ON VIEW_DANG_KY_GIANG_VIEN
BEGIN 
    UPDATE DAPH_DANGKY SET DIEMCK = :NEW.DIEMCK WHERE MASV = :OLD.MASV AND MAGV = :OLD.MAGV AND MAHP = :OLD.MAHP AND HK = :OLD.HK AND NAM = :OLD.NAM AND MACT = :OLD.MACT;
END;
/

CREATE OR REPLACE TRIGGER UPDATE_DIEMTK_VIEW_DANG_KY_GIANG_VIEN
INSTEAD OF UPDATE ON VIEW_DANG_KY_GIANG_VIEN
BEGIN 
    UPDATE DAPH_DANGKY SET DIEMTK = :NEW.DIEMTK WHERE MASV = :OLD.MASV AND MAGV = :OLD.MAGV AND MAHP = :OLD.MAHP AND HK = :OLD.HK AND NAM = :OLD.NAM AND MACT = :OLD.MACT;
END;
/

-- VIEW_PHAN_CONG_HOC_PHAN_VAN_PHONG_KHOA
CREATE OR REPLACE TRIGGER UPDATE_MAGV_VIEW_PHAN_CONG_HOC_PHAN_VAN_PHONG_KHOA
INSTEAD OF UPDATE ON VIEW_PHAN_CONG_HOC_PHAN_VAN_PHONG_KHOA
BEGIN
    UPDATE DAPH_PHANCONG SET MAGV = :NEW.MAGV WHERE MAGV = :OLD.MAGV AND MAHP = :OLD.MAHP AND HK = :OLD.HK AND NAM = :OLD.NAM AND MACT = :OLD.MACT;
END;
/

CREATE OR REPLACE TRIGGER UPDATE_MAHP_VIEW_PHAN_CONG_HOC_PHAN_VAN_PHONG_KHOA
INSTEAD OF UPDATE ON VIEW_PHAN_CONG_HOC_PHAN_VAN_PHONG_KHOA
BEGIN
    UPDATE DAPH_PHANCONG SET MAHP = :NEW.MAHP WHERE MAGV = :OLD.MAGV AND MAHP = :OLD.MAHP AND HK = :OLD.HK AND NAM = :OLD.NAM AND MACT = :OLD.MACT;
END;
/

CREATE OR REPLACE TRIGGER UPDATE_HK_VIEW_PHAN_CONG_HOC_PHAN_VAN_PHONG_KHOA
INSTEAD OF UPDATE ON VIEW_PHAN_CONG_HOC_PHAN_VAN_PHONG_KHOA
BEGIN
    UPDATE DAPH_PHANCONG SET HK = :NEW.HK WHERE MAGV = :OLD.MAGV AND MAHP = :OLD.MAHP AND HK = :OLD.HK AND NAM = :OLD.NAM AND MACT = :OLD.MACT;
END;
/

CREATE OR REPLACE TRIGGER UPDATE_NAM_VIEW_PHAN_CONG_HOC_PHAN_VAN_PHONG_KHOA
INSTEAD OF UPDATE ON VIEW_PHAN_CONG_HOC_PHAN_VAN_PHONG_KHOA
BEGIN
    UPDATE DAPH_PHANCONG SET NAM = :NEW.NAM WHERE MAGV = :OLD.MAGV AND MAHP = :OLD.MAHP AND HK = :OLD.HK AND NAM = :OLD.NAM AND MACT = :OLD.MACT;
END;
/

CREATE OR REPLACE TRIGGER UPDATE_MACT_VIEW_PHAN_CONG_HOC_PHAN_VAN_PHONG_KHOA
INSTEAD OF UPDATE ON VIEW_PHAN_CONG_HOC_PHAN_VAN_PHONG_KHOA
BEGIN
    UPDATE DAPH_PHANCONG SET MACT = :NEW.MACT WHERE MAGV = :OLD.MAGV AND MAHP = :OLD.MAHP AND HK = :OLD.HK AND NAM = :OLD.NAM AND MACT = :OLD.MACT;
END;
/

-- VIEW_PHAN_CONG_HOC_PHAN_DON_VI
CREATE OR REPLACE TRIGGER UPDATE_MAGV_VIEW_PHAN_CONG_HOC_PHAN_DON_VI
INSTEAD OF UPDATE ON VIEW_PHAN_CONG_HOC_PHAN_DON_VI
BEGIN
    UPDATE DAPH_PHANCONG SET MAGV = :NEW.MAGV WHERE MAGV = :OLD.MAGV AND MAHP = :OLD.MAHP AND HK = :OLD.HK AND NAM = :OLD.NAM AND MACT = :OLD.MACT;
END;
/

CREATE OR REPLACE TRIGGER UPDATE_MAHP_VIEW_PHAN_CONG_HOC_PHAN_DON_VI
INSTEAD OF UPDATE ON VIEW_PHAN_CONG_HOC_PHAN_DON_VI
BEGIN
    UPDATE DAPH_PHANCONG SET MAHP = :NEW.MAHP WHERE MAGV = :OLD.MAGV AND MAHP = :OLD.MAHP AND HK = :OLD.HK AND NAM = :OLD.NAM AND MACT = :OLD.MACT;
END;
/

CREATE OR REPLACE TRIGGER UPDATE_HK_VIEW_PHAN_CONG_HOC_PHAN_DON_VI
INSTEAD OF UPDATE ON VIEW_PHAN_CONG_HOC_PHAN_DON_VI
BEGIN
    UPDATE DAPH_PHANCONG SET HK = :NEW.HK WHERE MAGV = :OLD.MAGV AND MAHP = :OLD.MAHP AND HK = :OLD.HK AND NAM = :OLD.NAM AND MACT = :OLD.MACT;
END;
/

CREATE OR REPLACE TRIGGER UPDATE_NAM_VIEW_PHAN_CONG_HOC_PHAN_DON_VI
INSTEAD OF UPDATE ON VIEW_PHAN_CONG_HOC_PHAN_DON_VI
BEGIN
    UPDATE DAPH_PHANCONG SET NAM = :NEW.NAM WHERE MAGV = :OLD.MAGV AND MAHP = :OLD.MAHP AND HK = :OLD.HK AND NAM = :OLD.NAM AND MACT = :OLD.MACT;
END;
/

CREATE OR REPLACE TRIGGER UPDATE_MACT_VIEW_PHAN_CONG_HOC_PHAN_DON_VI
INSTEAD OF UPDATE ON VIEW_PHAN_CONG_HOC_PHAN_DON_VI
BEGIN
    UPDATE DAPH_PHANCONG SET MACT = :NEW.MACT WHERE MAGV = :OLD.MAGV AND MAHP = :OLD.MAHP AND HK = :OLD.HK AND NAM = :OLD.NAM AND MACT = :OLD.MACT;
END;
/


-- Các trigger để xóa dữ liệu 
CREATE OR REPLACE TRIGGER DELETE_VIEW_DANG_KY_HOC_PHAN_CON_MO
INSTEAD OF DELETE ON VIEW_DANG_KY_HOC_PHAN_CON_MO
BEGIN 
    DELETE FROM DAPH_DANGKY WHERE MASV = :OLD.MASV AND MAGV = :OLD.MAGV AND MAHP = :OLD.MAHP AND HK = :OLD.HK AND NAM = :OLD.NAM AND MACT = :OLD.MACT;
END;
/

CREATE OR REPLACE TRIGGER DELETE_VIEW_PHAN_CONG_HOC_PHAN_DON_VI
INSTEAD OF DELETE ON VIEW_PHAN_CONG_HOC_PHAN_DON_VI
BEGIN 
    DELETE FROM DAPH_PHANCONG WHERE MAGV = :OLD.MAGV AND MAHP = :OLD.MAHP AND HK = :OLD.HK AND NAM = :OLD.NAM AND MACT = :OLD.MACT;
END;
/

CREATE OR REPLACE TRIGGER DELETE_VIEW_PHAN_CONG_HOC_PHAN_VAN_PHONG_KHOA
INSTEAD OF DELETE ON VIEW_PHAN_CONG_HOC_PHAN_VAN_PHONG_KHOA
BEGIN
    DELETE FROM DAPH_PHANCONG WHERE MAGV = :OLD.MAGV AND MAHP = :OLD.MAHP AND HK = :OLD.HK AND NAM = :OLD.NAM AND MACT = :OLD.MACT;
END;
/
