-- Các câu lệnh STORED PROCEDURE
CREATE OR REPLACE PROCEDURE USP_CREATE_USER
    (USRNAME VARCHAR, USRPW VARCHAR)
AS
    STRSQL VARCHAR(2000);
BEGIN
    STRSQL :=  'ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE';
    EXECUTE IMMEDIATE (STRSQL);
    STRSQL :=  'CREATE USER ' || USRNAME || ' IDENTIFIED BY ' || USRPW;
    EXECUTE IMMEDIATE (STRSQL);
    STRSQL :=  'GRANT CONNECT TO '||USRNAME;
    EXECUTE IMMEDIATE (STRSQL);
    STRSQL :=  'ALTER SESSION SET "_ORACLE_SCRIPT" = FALSE';
    EXECUTE IMMEDIATE (STRSQL);
END;
/
CREATE OR REPLACE PROCEDURE USP_CREATE_ROLE
    (RLNAME VARCHAR)
AS
    STRSQL VARCHAR(2000);
BEGIN
    STRSQL :=  'ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE';
    EXECUTE IMMEDIATE (STRSQL);
    STRSQL :=  'CREATE ROLE '|| RLNAME;
    EXECUTE IMMEDIATE (STRSQL);
    STRSQL :=  'ALTER SESSION SET "_ORACLE_SCRIPT" = FALSE';
    EXECUTE IMMEDIATE (STRSQL);
END;
/

CREATE OR REPLACE PROCEDURE USP_DROP_ROLE
    (RL VARCHAR)
AS
    STRSQL VARCHAR(2000);
BEGIN
    STRSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE';
    EXECUTE IMMEDIATE (STRSQL);
    STRSQL := 'DROP ROLE ' || RL;
    EXECUTE IMMEDIATE (STRSQL);
    STRSQL :=  'ALTER SESSION SET "_ORACLE_SCRIPT" = FALSE';
    EXECUTE IMMEDIATE (STRSQL);
END;
/

CREATE OR REPLACE PROCEDURE USP_DROP_USER
    (USR VARCHAR)
AS
    STRSQL VARCHAR(2000);
BEGIN
    STRSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE';
    EXECUTE IMMEDIATE (STRSQL);
    STRSQL := 'DROP USER ' || USR;
    EXECUTE IMMEDIATE (STRSQL);
    STRSQL :=  'ALTER SESSION SET "_ORACLE_SCRIPT" = FALSE';
    EXECUTE IMMEDIATE (STRSQL);
END;
/

CREATE OR REPLACE PROCEDURE USP_ALTER_USER
    (USR VARCHAR, PASS VARCHAR)
AS
    STRSQL VARCHAR(2000);
BEGIN
    STRSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE';
    EXECUTE IMMEDIATE (STRSQL);
    STRSQL := 'ALTER USER ' || USR || ' IDENTIFIED BY ' || PASS;
    EXECUTE IMMEDIATE (STRSQL);
    STRSQL :=  'ALTER SESSION SET "_ORACLE_SCRIPT" = FALSE';
    EXECUTE IMMEDIATE (STRSQL);
END;
/


-- Phân hệ 2 
CREATE OR REPLACE PROCEDURE GAN_QUYEN_SINH_VIEN 
    (masv VARCHAR2)
AS
BEGIN
    EXECUTE IMMEDIATE ('GRANT CREATE SESSION TO ' || masv);
    EXECUTE IMMEDIATE ('GRANT SELECT ON DAPH_ADMIN1.DAPH_SINHVIEN TO ' || masv);
    EXECUTE IMMEDIATE ('GRANT SELECT ON DAPH_ADMIN1.DAPH_KHMO TO ' || masv);
    EXECUTE IMMEDIATE ('GRANT SELECT ON DAPH_ADMIN1.DAPH_HOCPHAN TO ' || masv);
    EXECUTE IMMEDIATE ('GRANT SELECT ON DAPH_ADMIN1.DAPH_DANGKY TO ' || masv);
    EXECUTE IMMEDIATE ('GRANT UPDATE (DCHI, DT) ON DAPH_ADMIN1.DAPH_SINHVIEN TO ' || masv);
    EXECUTE IMMEDIATE ('GRANT SELECT, INSERT, DELETE ON DAPH_ADMIN1.DAPH_DANGKY_SV TO ' || masv);
END;
/
