alter session set "_ORACLE_SCRIPT"=true;
-- ROLE NHANVIENCOBAN
GRANT CREATE SESSION TO DAPH_NHANVIENCOBAN;

-- Xem dòng dữ liệu của chính mình trong quan hệ NHANSU, có thể chỉnh sửa số điện thoai (DT) của chính mình (nếu số điện thoại có thay đổi).
CREATE OR REPLACE VIEW VIEW_THONG_TIN_NHAN_VIEN_CO_BAN AS
SELECT * 
FROM DAPH_NHANSU
WHERE MANV = SYS_CONTEXT('USERENV', 'SESSION_USER');
GRANT SELECT ON VIEW_THONG_TIN_NHAN_VIEN_CO_BAN TO DAPH_NHANVIENCOBAN;
GRANT UPDATE (DT) ON VIEW_THONG_TIN_NHAN_VIEN_CO_BAN TO DAPH_NHANVIENCOBAN;

-- Xem thông tin của tất cả SINHVIEN, ??NV?, HOCPHAN, KHMO.
GRANT SELECT ON DAPH_SINHVIEN TO DAPH_NHANVIENCOBAN;
GRANT SELECT ON DAPH_DONVI TO DAPH_NHANVIENCOBAN;
GRANT SELECT ON DAPH_HOCPHAN TO DAPH_NHANVIENCOBAN;
GRANT SELECT ON DAPH_KHMO TO DAPH_NHANVIENCOBAN;



-- ROLE GIANVIEN
GRANT CREATE SESSION TO DAPH_GIANGVIEN;

-- Như một người dùng có vai trò “Nhân viên cơ bản”
GRANT DAPH_NHANVIENCOBAN TO DAPH_GIANGVIEN;

-- Xem dữ liệu phân công giảng dạy liên quan đến bản thân mình (PHANCONG).
CREATE OR REPLACE VIEW VIEW_DU_LIEU_GIANG_DAY AS
SELECT *
FROM DAPH_PHANCONG
WHERE MAGV = SYS_CONTEXT('USERENV', 'SESSION_USER');
GRANT SELECT ON VIEW_DU_LIEU_GIANG_DAY TO DAPH_GIANGVIEN;

-- Xem dữ liệu trên quan hệ DANGKY liên quan đến các lớp học phần mà giảng viên được phân công giảng dạy.
CREATE OR REPLACE VIEW VIEW_DANG_KY_GIANG_VIEN AS
SELECT *
FROM DAPH_DANGKY
WHERE MAGV = SYS_CONTEXT('USERENV', 'SESSION_USER');
GRANT SELECT ON VIEW_DANG_KY_GIANG_VIEN TO DAPH_GIANGVIEN;

-- Cập nhật dữ liệu tại các trường liên quan điểm số (trong quan hệ ĐANGKY) của các
-- sinh viên có tham gia lớp học phần mà giảng viên đó được phân công giảng dạy. Các
-- trường liên quan điểm số bao gồm: ĐIEMTH, ĐIEMQT, ĐIEMCK, ĐIEMTK.
GRANT UPDATE (DIEMTH, DIEMQT, DIEMCK, DIEMTK) ON VIEW_DANG_KY_GIANG_VIEN TO DAPH_GIANGVIEN;



--  ROLE GIAOVU
GRANT CREATE SESSION TO DAPH_GIAOVU;

-- Như một người dùng có vai trò “Nhân viên cơ bản”
GRANT DAPH_NHANVIENCOBAN TO DAPH_GIAOVU;

-- Xem, Thêm mới hoặc Cập nhật dữ liệu trên các quan hệ SINHVIEN, ĐONVI, HOCPHAN, KHMO, theo yêu cầu của trưởng khoa.
GRANT SELECT, INSERT, UPDATE ON DAPH_SINHVIEN TO DAPH_GIAOVU;
GRANT SELECT, INSERT, UPDATE ON DAPH_DONVI TO DAPH_GIAOVU;
GRANT SELECT, INSERT, UPDATE ON DAPH_HOCPHAN TO DAPH_GIAOVU;
GRANT SELECT, INSERT, UPDATE ON DAPH_KHMO TO DAPH_GIAOVU;

-- Xem dữ liệu trên toàn bộ quan hệ PHANCONG. Tuy nhiên, chỉ được sửa trên các dòng
-- dữ liệu phân công liên quan các học phần do “Văn phòng khoa” phụ trách phân công
-- giảng dạy, thừa hành người trưởng đơn vị tương ứng là trưởng khoa.
GRANT SELECT ON DAPH_PHANCONG TO DAPH_GIAOVU;
CREATE OR REPLACE VIEW VIEW_PHAN_CONG_HOC_PHAN_VAN_PHONG_KHOA AS
SELECT PC.MAGV, PC.MAHP, PC.HK, PC.NAM, PC.MACT
FROM DAPH_PHANCONG PC, DAPH_HOCPHAN HP, DAPH_DONVI DV
WHERE DV.MADV = HP.MADV AND DV.TENDV = N'Văn phòng khoa' AND
        HP.MAHP = PC.MAHP;
GRANT SELECT, UPDATE ON VIEW_PHAN_CONG_HOC_PHAN_VAN_PHONG_KHOA TO DAPH_GIAOVU;

-- Xóa hoặc Thêm mới dữ liệu trên quan hệ ĐANGKY theo yêu cầu của sinh viên trong 
-- khoảng thời gian còn cho hiệu chỉnh đăng ký, xem điều kiện có thể hiệu chỉnh đăng ký 
-- học phần được mô tả bên dưới. 
CREATE OR REPLACE VIEW VIEW_DANG_KY_HOC_PHAN_CON_MO AS
SELECT *
FROM DAPH_DANGKY
WHERE EXTRACT(MONTH FROM SYSDATE) IN (1, 5, 9)
AND NAM = EXTRACT(YEAR FROM SYSDATE)
AND EXTRACT(DAY FROM SYSDATE) BETWEEN 1 AND 14;
GRANT INSERT, DELETE ON VIEW_DANG_KY_HOC_PHAN_CON_MO TO DAPH_GIAOVU;

GRANT SELECT, INSERT, DELETE ON DAPH_ADMIN1.DAPH_DANGKY_SV TO DAPH_GIAOVU;
	


--  ROLE TRUONGDONVI
GRANT CREATE SESSION TO DAPH_TRUONGDONVI;

-- Như một người dùng có vai trò “Giảng viên”
GRANT DAPH_GIANGVIEN TO DAPH_TRUONGDONVI;

-- Thêm, Xóa, Cập nhật dữ liệu trên quan hệ PHANCONG, đối với các học phần được phụ trách chuyên môn bởi đơn vị mà mình làm trưởng,
CREATE OR REPLACE VIEW VIEW_PHAN_CONG_HOC_PHAN_DON_VI AS
SELECT PC.MAGV, PC.MAHP, PC.HK, PC.NAM, PC.MACT
FROM DAPH_PHANCONG PC, DAPH_HOCPHAN HP, DAPH_DONVI DV, DAPH_NHANSU NS
WHERE NS.MANV = SYS_CONTEXT('USERENV', 'SESSION_USER') AND NS.MADV = DV.MADV AND
    HP.MADV = DV.MADV AND HP.MAHP = PC.MAHP AND NS.MANV = DV.TRGDV;
GRANT INSERT, DELETE, UPDATE ON VIEW_PHAN_CONG_HOC_PHAN_DON_VI TO DAPH_TRUONGDONVI;

-- Được xem dữ liệu phân công giảng dạy của các giảng viên thuộc các đơn vị mà mình làm trưởng.
GRANT SELECT ON VIEW_PHAN_CONG_HOC_PHAN_DON_VI TO DAPH_TRUONGDONVI;



-- ROLE TRUONGKHOA
GRANT CREATE SESSION TO DAPH_TRUONGKHOA;

-- Như một người dùng có vai trò “Giảng viên”
GRANT DAPH_GIANGVIEN TO DAPH_TRUONGKHOA;

-- Thêm, Xóa, Cập nhật dữ liệu trên quan hệ PHANCONG đối với các học phần quản lý bởi đơn vị “Văn phòng khoa”.
GRANT SELECT, INSERT, DELETE, UPDATE ON VIEW_PHAN_CONG_HOC_PHAN_VAN_PHONG_KHOA TO DAPH_TRUONGKHOA;

-- Được quyền Xem, Thêm, Xóa, Cập nhật trên quan hệ NHANSU.
GRANT SELECT, INSERT, DELETE, UPDATE ON DAPH_NHANSU TO DAPH_TRUONGKHOA;

-- Được quyền Xem (không giới hạn) dữ liệu trên toàn bộ lược đồ CSDL.
GRANT SELECT ON DAPH_DANGKY TO DAPH_TRUONGKHOA;
GRANT SELECT ON DAPH_PHANCONG TO DAPH_TRUONGKHOA;

