ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

-- RUN THIS IF DAPH_ADMIN IS NOT CREATED YET
/*
CREATE USER DAPH_ADMIN IDENTIFIED BY daph_admin;
GRANT CREATE SESSION TO DAPH_ADMIN;
GRANT DBA TO DAPH_ADMIN;
GRANT AUDIT SYSTEM TO DAPH_ADMIN;
GRANT EXECUTE ANY PROCEDURE TO DAPH_ADMIN;
GRANT EXECUTE ON DBMS_FGA TO DAPH_ADMIN;
*/

-- STANDARD AUDITING
-- ENABLE AUDIT ON SENSITIVE TABLES
-- MỞ AUDIT TRÊN DỮ LIỆU NHẠY CẢM
-- AUDIT SESSION;
AUDIT INSERT, DELETE, UPDATE ON DAPH_ADMIN1.DAPH_DANGKY BY ACCESS;

AUDIT INSERT, DELETE, UPDATE ON DAPH_ADMIN1.DAPH_PHANCONG BY ACCESS;

AUDIT INSERT, DELETE, UPDATE ON DAPH_ADMIN1.DAPH_KHMO BY ACCESS;

AUDIT SELECT, INSERT, UPDATE, DELETE ON DAPH_ADMIN1.DAPH_SINHVIEN BY ACCESS;

--AUDIT UPDATE ON DAPH_ADMIN.VIEW_PHAN_CONG_HOC_PHAN_VAN_PHONG_KHOA BY SESSION;

--AUDIT INSERT, DELETE, UPDATE ON DAPH_ADMIN.VIEW_DANG_KY_HOC_PHAN_CON_MO BY SESSION;

--AUDIT SELECT, INSERT, UPDATE, DELETE ON DAPH_ADMIN.VIEW_DANG_KY_GIANG_VIEN;

-- DISABLE AUDIT ON SENSITIVE TABLES
-- BỎ AUDIT TRÊN DỮ LIỆU
/*
NOAUDIT SESSION;
NOAUDIT ALL ON DAPH_ADMIN.DAPH_DANGKY;

NOAUDIT ALL ON DAPH_ADMIN.DAPH_PHANCONG;

NOAUDIT ALL ON DAPH_ADMIN.DAPH_KHMO;

NOAUDIT INSERT, UPDATE, DELETE ON DAPH_ADMIN1.DAPH_DANGKY;

NOAUDIT INSERT, UPDATE, DELETE ON DAPH_ADMIN1.DAPH_PHANCONG;

NOAUDIT INSERT, UPDATE, DELETE ON DAPH_ADMIN1.DAPH_KHMO;

NOAUDIT SELECT, INSERT, UPDATE, DELETE ON DAPH_ADMIN1.DAPH_SINHVIEN;

NOAUDIT ALL ON VIEW_PHAN_CONG_HOC_PHAN_VAN_PHONG_KHOA;

NOAUDIT ALL ON VIEW_DANG_KY_HOC_PHAN_CON_MO;
*/
-- FINE-GRAINED AUDIT
-- XÓA POLICY
/*
BEGIN
    DBMS_FGA.DROP_POLICY (
        object_schema => 'DAPH_ADMIN1',
        object_name => 'DAPH_DANGKY',
        policy_name => 'AUD_U_DANGKY'
        );
END;
/

BEGIN
    DBMS_FGA.DROP_POLICY (
        object_schema => 'DAPH_ADMIN1',
        object_name => 'DAPH_NHANSU',
        policy_name => 'AUD_R_NHANSU'
        );
END;
/
*/
-- A) FGA TRÊN DANGKY CÁC HÀNH VI CẬP NHẬT TẠI CÁC TRƯỜNG LIÊN QUAN ĐẾN ĐIỂM SỐ NHƯNG NGƯỜI ĐÓ KHÔNG THUỘC VAI TRÒ GIẢNG VIÊN
BEGIN    
    DBMS_FGA.ADD_POLICY(
        object_schema => 'DAPH_ADMIN1',
        object_name => 'DAPH_DANGKY',
        policy_name => 'AUD_U_DANGKY',
        audit_condition => 'SYS_CONTEXT(''USERENV'', ''SESSION_USER'') NOT IN (SELECT MANV FROM DAPH_NHANSU WHERE VAITRO = N''Giảng viên'')',
        audit_column => 'DIEMTH,DIEMQT,DIEMCK,DIEMTK',
        enable => TRUE,
        statement_types => 'UPDATE',
        audit_trail => DBMS_FGA.DB
    );
END;
/
-- B) FGA HÀNH VI CỦA NGƯỜI DÙNG NÀY CÓ THỂ ĐỌC TRÊN TRƯỜNG PHỤ CẤP CỦA NGƯỜI KHÁC Ở QUAN HỆ NHANSU (FGA TRÊN NHANSU)
BEGIN
    DBMS_FGA.ADD_POLICY(
        object_schema => 'DAPH_ADMIN1',
        object_name => 'DAPH_NHANSU',
        policy_name => 'AUD_R_NHANSU',
        audit_condition => 'MANV!=SYS_CONTEXT(''USERENV'', ''SESSION_USER'')',
        audit_column => 'PHUCAP',
        enable => TRUE,
        statement_types => 'SELECT',
        audit_trail => DBMS_FGA.DB
    );
END;
/

-- TRUY VẤN NHẬT KÝ
-- STANDARD:
SELECT *
FROM SYS.DBA_AUDIT_TRAIL;

SELECT USERNAME,TIMESTAMP,OBJ_NAME,ACTION_NAME,SQL_TEXT
FROM SYS.DBA_AUDIT_TRAIL;

-- TÌM KIẾM THEO BẢNG:
SELECT USERNAME,TIMESTAMP,OBJ_NAME,ACTION_NAME,SQL_TEXT
FROM SYS.DBA_AUDIT_TRAIL WHERE OBJ_NAME = 'DAPH_DANGKY';

-- TÌM KIẾM CÁC BẢNG ĐƯỢC AUDIT STANDARD
SELECT * FROM SYS.DBA_OBJ_AUDIT_OPTS WHERE OWNER = 'DAPH_ADMIN';

-- FGA:
SELECT DB_USER, TIMESTAMP, OBJECT_NAME,STATEMENT_TYPE,SQL_TEXT FROM SYS.DBA_FGA_AUDIT_TRAIL;

-- CHÍNH SÁCH 1:
SELECT DB_USER, TIMESTAMP, OBJECT_NAME,STATEMENT_TYPE,SQL_TEXT FROM SYS.DBA_FGA_AUDIT_TRAIL
WHERE OBJECT_NAME = 'DAPH_DANGKY';

-- CHÍNH SÁCH 2:
SELECT DB_USER, TIMESTAMP, OBJECT_NAME,STATEMENT_TYPE,SQL_TEXT FROM SYS.DBA_FGA_AUDIT_TRAIL
WHERE OBJECT_NAME = 'DAPH_NHANSU';

DELETE FROM SYS.DBA_AUDIT_TRAIL;